DROP DATABASE OKATTER;
CREATE DATABASE OKATTER;

DROP USER IF EXISTS 'okatter-user'@'localhost';
CREATE USER IF NOT EXISTS 'okatter-user'@'localhost' IDENTIFIED BY 'okatter';
ALTER USER 'okatter-user'@'localhost' IDENTIFIED WITH MYSQL_NATIVE_PASSWORD by 'okatter';
GRANT SELECT, INSERT, UPDATE, DELETE ON OKATTER.* TO 'okatter-user'@'localhost';

USE OKATTER;

CREATE TABLE USERS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	NAME VARCHAR(64) NOT NULL
);

CREATE TABLE TWEET(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(64) NOT NULL,
	BODY VARCHAR(255) NOT NULL,
	USER_ID INT NOT NULL,
	UPDATE_AT TIMESTAMP NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);